### PR TITLE
Add support for OCaml 5.00

### PR DESCRIPTION
**Pull request by kit-ty-kate**
PR on top of #2 to fix the build failure with OCaml 5.00

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @garrigue

**Comment by garrigue** [comment]
This seems to introduce also a dependency on findlib.
I'll try to make the code compatible with other versions of ocaml.

**Comment by kit-ty-kate** [comment]
> This seems to introduce also a dependency on findlib.

How so? As far as I know lablgl already depends on ocamlfind

**Comment by kit-ty-kate** [comment]
Ah nevermind I was looking at the wrong opam file

**Comment by garrigue** [comment]
I agree that it is reasonable to use findlib with ocaml 5.00, but I would prefer to keep backward compatibility.
But this may be difficult without configuration, so it might be ok to change the requirements.

**Comment by kit-ty-kate** [comment]
Rebased on top of master

**Comment by sanette** [comment]
Hi, is there an estimated time for ocaml 5.00 support?

**Comment by garrigue** [comment]
OCaml 5.0.0 is already supported.
I have no plan yet to merge this PR for other reasons, but this shouldn't prevent lablgl from compiling onto 5.0.0.

**Comment by sanette** [comment]
> OCaml 5.0.0 is already supported.

Oh. I was using the opam package, so I guess the opam pacakge is too old?
```
$ opam update
$ opam show lablgl

<><> lablgl: information on all versions ><><><><><><><><><><><><><><><><><><><>
name                   lablgl
all-installed-versions 1.06 [4.08.1 4.13.0 4.14.0]
all-versions           1.04.20120306  1.05  1.06

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version      1.06
repository   default
url.src      "https://github.com/garrigue/lablgl/archive/v1.06.tar.gz"
url.checksum "md5=8ee7a37b016095c4f7cd066f0ebd4436"
homepage     "https://github.com/garrigue/lablgl"
bug-reports  "https://github.com/garrigue/lablgl/issues"
dev-repo     "git+https://github.com/garrigue/lablgl.git"
authors      "Jacques Garrigue et al., Nagoya University"
maintainer   "garrigue@math.nagoya-u.ac.jp"
license      "BSD-3-Clause"
flags        light-uninstall
depends      "ocaml" {>= "4.03" & < "5.0"}
synopsis     Interface to OpenGL
description  Interface between OCaml and OpenGL, including Togl wrapper for use
             with LablTk, and LablGlut wrapper for direct use using the glut
             library.
```

```

**Comment by garrigue** [comment]
My bad. I got confused between versions. I will release ASAP.

**Comment by garrigue** [comment]
See https://github.com/ocaml/opam-repository/pull/23384 for the new release.

**Pull request merged**
