### PR TITLE
Activate CAML_NAME_SPACE

### PR DESCRIPTION
**Pull request by kit-ty-kate**
This brings the compatibility with ocaml-multicore (where modify isn't currently defined) and OCaml 5.0 (where, with a bit of luck compatibility macros are going away anyway)

Side note: the big change in `LablGlut/src/wrap_gl.c` is due to the file changing from `dos` format to `unix`, you can focus on the real change in the file with the "Hide whitespace change" feature of Github:
scrn-2020-12-03-16-37-26

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @garrigue

**Comment by garrigue** [comment]
@kit-ty-kate Something strange occurs in `LablGlut/wrap_gl.c`: all the code is changed. A problem in the diff?

**Comment by kit-ty-kate** [comment]
It’s a switch from windows file format to unix I believe

**Comment by garrigue** [comment]
I see. In that case it would be sufficient to split the commits.

**Comment by garrigue** [comment]
Thanks.

**Pull request merged**
